language: generic

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - linux
  - osx

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # Python
      - python3
      # PHP
      - php5-cli
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libgd2-xpm
      - ia32-libs
      - ia32-libs-multiarch

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
      sudo add-apt-repository ppa:haxe/releases -y;
      sudo apt-get update;
      sudo apt-get install haxe -y;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew install phantomjs;
      brew install python3;
      brew install haxe;
    fi
  # Check the installed versions
  - neko -version
  - haxe -version
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install haxelibs
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe build-interp.hxml
  - haxe build-neko.hxml         && neko bin/HelloWorld.n
  - haxe build-js.hxml           && node bin/HelloWorld.js
                                 && haxe phantomjs/run.hxml bin/HelloWorld.js
  - haxe build-java.hxml         && java -jar bin/HelloWorld.jar
  - haxe build-php.hxml          && php bin/index.php
  - haxe build-cs.hxml           && mono bin/bin/HelloWorld.exe
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/HelloWorld.swf
  - haxe build-cpp.hxml          && ./bin/HelloWorld
  - haxe build-python.hxml       && python3 bin/HelloWorld.py
