language: haxe

haxe:
  - "3.1.3"
  - development

os:
  - osx

addons:
  apt:
    packages:
      - python3
      - php-zeroc-ice # use it to install php5 for now

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; sudo apt-get install mono-devel mono-mcs -qq; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; brew install mono python3; fi
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe build-interp.hxml
  - haxe build-neko.hxml && neko bin/HelloWorld.n
  - haxe build-js.hxml && node bin/HelloWorld.js
  - haxe build-java.hxml && java -jar bin/HelloWorld.jar
  - haxe build-php.hxml && php bin/index.php
  - haxe build-cs.hxml && mono bin/bin/HelloWorld.exe
  - haxe build-flash.hxml # Flash testing is hard to setup. Just run the haxe compiler for now
  - haxe build-cpp.hxml && ./bin/HelloWorld
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then haxe build-python.hxml && python3 bin/HelloWorld.py; fi

cache:
  directories:
    - $HOME/haxe/lib
